name: Build QuokKM5 firmware

on:
  push:
  workflow_dispatch:

jobs:
  build_quokkadb:
    name: Build firmware on Ubuntu 22.04
    runs-on: ubuntu-22.04

    steps:
      - name: Check out code from GitHub
        uses: actions/checkout@v4
        with:
          path: quokkm5
          fetch-depth: "0"

      - name: Install packages
        run: |
            sudo apt-get update      
            sudo apt-get install -y python3-pip

      - name: Install platformio
        run: |
          sudo pip install platformio

      - name: Build firmware
        run: |
          cd quokkm5/src/firmware
          pio run -ve quokkm5

      - name: Rename firmware files
        run: |
          cd quokkm5/src/firmware
          utils/rename_quokkm5_binaries.sh

      - name: Upload binaries into build artifacts
        uses: actions/upload-artifact@v4
        with: 
          path: quokkm5/src/firmware/distrib/*
          name: QuokKM5 binaries

      - name: Upload to latest release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: github.ref == 'refs/heads/main'
        run: |
          cd quokkm5/src/firmware
          git tag -d latest
          git tag latest
          git push origin --force latest
          cd distrib
          gh api repos/${GITHUB_REPOSITORY}/releases/tags/latest | jq -r '.assets[] | [.url] | @tsv' | xargs -n 1 gh api -X DELETE || true
          gh release upload --repo ${GITHUB_REPOSITORY} --clobber latest *

      - name: Upload to newly created release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        run: |
          cd quokkm5/src/firmware/distrib
          RELEASE=$(basename ${{github.ref}})
          gh release upload --repo ${GITHUB_REPOSITORY} $RELEASE *
